### ISSUE TITLE
ossl support?

### ISSUE THREAD

**Issue by geirnoklebye** [buildersbrewery/lsl-for-ultraedit#2]
Hi, and thanks for all the effort of maintaining this for lsl and UltraEdit. 

Is there any chance you would be able to add ossl support as well. These are scripting extensions for opensim not supported by Linden Lab, but still works in lsl script in opensim environment?

http://opensimulator.org/wiki/OSSL_Implemented

**Comment by buildersbrewery** [comment]
I won't be adding OSSL support here. Feel free to fork this repo and add it to your fork. If you need help with the OSSL keywords, have a look at [kwdb](https://bitbucket.org/Sei_Lisa/kwdb).
